export  const CategoriesList=[
    {
        id:21,
        catName:"Best of Electronics",
        catNames:[
            {
                id:1,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:2,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:3,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:4,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:5,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:6,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
          
        ]
    },
    {
        id:22,
        catName:"Beauty, Food, Toys & more",
        catNames:[
            {
                id:1,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:2,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:3,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:4,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:5,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:6,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
          
        ]
    },
    {
        id:23,
        catName:"Gifts for Your Loved Ones",
        catNames:[
            {
                id:1,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:2,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:3,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:4,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:5,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:6,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
          
        ]
    },
    {
        id:24,
        catName:"Sports, Healthcare & more",
        catNames:[
            {
                id:1,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:2,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:3,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:4,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:5,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:6,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
          
        ]
    },
    {
        id:25,
        catName:"Home Decor & Furnishings",
        catNames:[
            {
                id:1,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:2,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:3,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:4,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:5,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:6,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
          
        ]
    },
    {
        id:26,
        catName:"Health & Wellness",
        catNames:[
            {
                id:1,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:2,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:3,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:4,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:5,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:6,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
          
        ]
    },
    {
        id:27,
        catName:"Home & Kitchen Essentials",
        catNames:[
            {
                id:1,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:2,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:3,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:4,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:5,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
            {
                id:6,
                image:"https://tiimg.tistatic.com/fp/1/007/951/6-6-inch-screen-size-full-hd-128-gb-internal-storage-vivo-y33t-mobile-phone-447.jpg",
                name:"Mobiles",
                price:10000
            },
          
        ]
    },
]